### PR TITLE
Feature - PHP CodeSniffer support

### PR DESCRIPTION
**Pull request by akalongman**

### CODE REVIEW

**Comment by e1himself** [comment]
@akalongman let's move this phpcs configuration to a separate repository and link as composer dependency. 

Please use this repo I've just created:
https://github.com/prezly/code-style

**Comment by e1himself** [comment]
btw @akalongman great job! Thanks :+1:

**Comment by akalongman** [comment]
@e1himself why we need to move phpcs configuration (there are just one file) to separate repository?

**Comment by e1himself** [comment]
@akalongman Do you think that's a bad idea?

My arguments are:
We need this code style here and we need it inside prezly/prezly. 
If we want to fix/change something in future, we'll need to do that in two repos.

Do you see any problems with that?

**Comment by akalongman** [comment]
And we will pass path to phpcs.xml file located in vendor folder?

**Comment by akalongman** [comment]
Also I think configs will be different, e.g. excluded folders/files etc.

**Pull request merged**
